/**
 * Core Flashcard System Types
 *
 * Architecture Philosophy:
 * - Cards = data (fields as key-value pairs)
 * - Templates = presentation (HTML/CSS) + field schema
 * - Interactions = field-level behaviors (type-answer, cloze, etc.)
 * - Everything is extensible for future expansion
 */

// ============================================================================
// FIELD TYPES & INTERACTIONS
// ============================================================================

export type FieldType =
  | 'text'              // Plain text input
  | 'richtext'          // HTML content (TipTap/Quill)
  | 'code'              // Code editor with syntax highlighting
  | 'latex'             // Math equations (KaTeX)
  | 'media'             // File upload (image/audio/video)
  | 'cloze';            // Special: supports {{c1::deletion}} syntax

export type InteractionType =
  | 'display'           // Just show the content (default)
  | 'type-answer'       // User types answer, we validate
  | 'reveal-cloze'      // Show [...], click to reveal
  | 'reveal-list'       // Progressive bullet point reveal
  | 'image-occlusion'   // SVG masks over image
  | 'select-multiple'   // Multiple choice (future)
  | 'record-audio';     // Voice recording (future)

export interface TemplateField {
  name: string;           // 'Front', 'Back', 'Pronunciation', 'Hint', etc.
  type: FieldType;
  required: boolean;
  placeholder?: string;

  // Field-level interaction settings
  interaction?: FieldInteraction;

  // For media fields
  accepts?: string[];     // ['image/*', 'audio/*', 'video/*']
}

export interface FieldInteraction {
  type: InteractionType;
  settings: InteractionSettings;
}

// ============================================================================
// INTERACTION SETTINGS (Field-Specific Behaviors)
// ============================================================================

export type InteractionSettings =
  | TypeAnswerSettings
  | RevealClozeSettings
  | RevealListSettings
  | ImageOcclusionSettings
  | DisplaySettings;

export interface TypeAnswerSettings {
  type: 'type-answer';

  // Matching rules
  caseSensitive: boolean;
  ignorePunctuation: boolean;
  acceptTypos: boolean;           // Fuzzy matching
  typoThreshold: number;          // Max Levenshtein distance (default: 2)

  // Multiple correct answers
  alternatives?: string[];

  // Display
  showTypedAnswer: boolean;
  highlightDifferences: boolean;  // Character-by-character diff
}

export interface RevealClozeSettings {
  type: 'reveal-cloze';
  revealOneAtATime: boolean;
  showHints: boolean;
  hintCharacterCount: number;     // How many chars to reveal (default: 1)
}

export interface RevealListSettings {
  type: 'reveal-list';
  revealOrder: 'sequential' | 'random';
  autoReveal: boolean;
  autoRevealDelay: number;        // Milliseconds
}

export interface ImageOcclusionSettings {
  type: 'image-occlusion';
  occlusions: OcclusionRect[];    // Generated by editor tool
  revealOneAtATime: boolean;
  showLabels: boolean;
}

export interface OcclusionRect {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
  label?: string;
}

export interface DisplaySettings {
  type: 'display';
  autoPlayAudio?: boolean;        // For media fields
}

// ============================================================================
// CARD TEMPLATE
// ============================================================================

export interface CardTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;               // 'Language', 'Science', 'Math', 'General'

  // Field schema - what fields does this template expect?
  fields: TemplateField[];

  // Rendered output (HTML/CSS)
  // Builder is just a UI tool - we only store the generated HTML!
  front: string;                  // HTML with {{Field}} placeholders
  back: string;
  css: string;
  js?: string;                    // Optional JavaScript for custom interactions

  // Metadata
  tags: string[];
  isBuiltIn: boolean;
  isPublic?: boolean;             // For community sharing (future)

  createdAt: number;
  updatedAt: number;
  createdBy?: string;             // User ID (future)
}

// ============================================================================
// CARD
// ============================================================================

export type FieldValue = string | number | boolean | string[] | null;

export interface Card {
  id: string;
  deckId: string;
  templateId: string;             // Which template renders this card

  // Field data (flexible key-value)
  // Examples:
  // - Basic: { Front: "Question", Back: "Answer" }
  // - Language: { English: "Hello", Spanish: "Hola", Audio: "hello.mp3" }
  // - Cloze: { Text: "The {{c1::mitochondria}} is the powerhouse" }
  fields: Record<string, FieldValue>;

  // Media file references (Files as Entity Properties pattern)
  // fieldName -> storage key (e.g., 'Audio' -> 'core-flashcards:media:card-123:Audio')
  mediaFiles?: Record<string, string>;

  // Spaced repetition state
  state: CardState;

  // Organization
  tags: string[];

  // Metadata
  createdAt: number;
  updatedAt: number;
}

// ============================================================================
// CARD STATE (Spaced Repetition)
// ============================================================================

export interface CardState {
  // SM-2 algorithm fields
  easeFactor: number;             // Default: 2.5 (250%)
  interval: number;               // Days until next review
  dueDate: number;                // Timestamp

  // Counts
  reviewCount: number;
  lapseCount: number;

  // Learning stage
  stage: 'new' | 'learning' | 'review' | 'relearning';

  // Learning steps progress (for new/relearning cards)
  learningStep: number;           // Current step index in steps array

  // Last review
  lastReviewedAt?: number;
  lastGrade?: 1 | 2 | 3 | 4;      // Again, Hard, Good, Easy
}

// ============================================================================
// DECK
// ============================================================================

export interface Deck {
  id: string;
  name: string;
  description?: string;

  // Integration with documents plugin
  folderId?: string | null;       // Can live in document folders

  // Settings
  settings: DeckSettings;

  // Active status (for "Today's Focus" widget)
  isActive: boolean;

  // Statistics (cached, updated after each study session)
  stats: DeckStats;

  // Metadata
  createdAt: number;
  updatedAt: number;

  // Community features (future)
  isPublic?: boolean;
  publishedAt?: number;
  downloadCount?: number;
  averageRating?: number;
}

// ============================================================================
// DECK SETTINGS
// ============================================================================

export type SpacedRepetitionPreset = 'relaxed' | 'balanced' | 'intense' | 'custom';

export interface DeckSettings {
  // Algorithm
  algorithm: 'sm2' | 'custom';    // Extensible for future algorithms
  preset: SpacedRepetitionPreset;

  // SM-2 Parameters (only used if preset = 'custom')
  newCardSteps: number[];         // [1, 10] = 1 min, 10 min
  graduatingInterval: number;     // Days
  easyInterval: number;           // Days
  startingEase: number;           // 250 = 250%
  easyBonus: number;              // 130 = 130%
  intervalModifier: number;       // 100 = 100%
  maxInterval: number;            // 36500 = 100 years
  hardInterval: number;           // 120 = 120%

  // Lapse settings
  relearningSteps: number[];      // [10] = 10 min
  newInterval: number;            // 0 = reset to 0%
  minimumInterval: number;        // 1 day
  leechThreshold: number;         // 8 lapses = leech

  // Daily limits
  newCardsPerDay: number;
  reviewsPerDay: number;

  // Display
  showHints: boolean;
  autoPlayAudio: boolean;
  randomizeCardOrder: boolean;

  // Advanced
  enableReverseCards: boolean;    // Auto-generate reverse cards
  buryRelatedCards: boolean;      // Don't show related in same session
}

// ============================================================================
// DECK STATISTICS
// ============================================================================

export interface DeckStats {
  // Card counts by state
  totalCards: number;
  newCards: number;
  learningCards: number;
  reviewCards: number;

  // Due today
  dueToday: number;

  // Mastery (cards with interval > 21 days)
  masteredCards: number;

  // Performance metrics
  averageRetention: number;       // % cards answered correctly
  averageEase: number;            // Average ease factor

  // Study time
  totalStudyTime: number;         // Milliseconds
  lastStudiedAt?: number;

  // Streaks
  currentStreak: number;          // Days
  longestStreak: number;
}

// ============================================================================
// STUDY SESSION
// ============================================================================

export type StudyMode =
  | 'spaced-repetition'           // Smart scheduling (SM-2)
  | 'classic'                     // Manual pace, no scheduling
  | 'shuffle'                     // Random order
  | 'cram'                        // Quick review, no scheduling changes
  | 'match'                       // Game: match terms/definitions
  | 'type-race'                   // Game: type before timer
  | 'memory-grid'                 // Game: flip and match
  | 'write';                      // Practice: type all answers

export interface StudySession {
  id: string;
  deckId: string;

  // Session metadata
  startTime: number;
  endTime?: number;
  mode: StudyMode;

  // Cards reviewed
  cardsReviewed: CardReview[];

  // Performance summary
  totalCards: number;
  correctCards: number;
  againCount: number;
  hardCount: number;
  goodCount: number;
  easyCount: number;

  // Time tracking
  totalTime: number;              // Milliseconds
  averageTimePerCard: number;
}

export interface CardReview {
  cardId: string;
  grade: 1 | 2 | 3 | 4;           // Again, Hard, Good, Easy
  timeSpent: number;               // Milliseconds
  previousInterval: number;
  newInterval: number;
  previousEase: number;
  newEase: number;
  timestamp: number;
}

// ============================================================================
// USER STATISTICS (Global)
// ============================================================================

export interface UserStatistics {
  userId: string;

  // Overall progress
  totalDecks: number;
  totalCards: number;
  masteredCards: number;
  cardsStudiedToday: number;

  // Streaks
  currentStreak: number;
  longestStreak: number;
  lastStudyDate?: number;         // YYYY-MM-DD format

  // Study history (for GitHub-style heatmap)
  dailyReviews: Record<string, number>;  // 'YYYY-MM-DD' -> card count

  // Performance
  totalReviews: number;
  averageRetention: number;
  totalStudyTime: number;         // Milliseconds

  // Per-deck statistics
  deckStats: Record<string, DeckStats>;

  // Achievements (future)
  achievements?: Achievement[];
}

export interface Achievement {
  id: string;
  name: string;
  description: string;
  icon: string;
  unlockedAt: number;
  progress?: number;              // For progressive achievements (0-100)
}

// ============================================================================
// IMPORT/EXPORT FORMATS
// ============================================================================

export interface ExportData {
  version: string;                // Data format version (for migrations)
  exportedAt: number;

  // Core data
  decks: Deck[];
  cards: Card[];
  templates: CardTemplate[];

  // Media files (base64 encoded for portability)
  media: Record<string, MediaFile>;

  // Study history (optional)
  sessions?: StudySession[];
  statistics?: UserStatistics;
}

export interface MediaFile {
  data: string;                   // Base64 encoded
  mimeType: string;
  fileName: string;
  size: number;
}

// Anki compatibility structures
export interface AnkiNote {
  id: number;
  guid: string;
  mid: number;                    // Model (template) ID
  mod: number;                    // Modification timestamp
  usn: number;                    // Update sequence number
  tags: string;                   // Space-separated
  flds: string;                   // Tab-separated field values
  sfld: string;                   // Sort field
  csum: number;                   // Checksum
  flags: number;
  data: string;
}

export interface AnkiCard {
  id: number;
  nid: number;                    // Note ID
  did: number;                    // Deck ID
  ord: number;                    // Ordinal
  mod: number;
  usn: number;
  type: number;                   // 0=new, 1=learning, 2=review, 3=relearn
  queue: number;
  due: number;
  ivl: number;                    // Interval
  factor: number;                 // Ease factor (2500 = 250%)
  reps: number;
  lapses: number;
  left: number;
  odue: number;
  odid: number;
  flags: number;
  data: string;
}

// ============================================================================
// VALIDATION RESULTS
// ============================================================================

export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
}

export interface ValidationError {
  field: string;
  message: string;
}

// ============================================================================
// FOLDER INTEGRATION
// ============================================================================

/**
 * Folder tree node with deck count
 * Re-uses Documents plugin Folder type with additional metadata
 */
export interface FolderTreeNode {
  id: string;
  name: string;
  parentId: string | null;
  order: number;
  depth: number;
  color?: string;
  icon?: string;
  tags: string[];
  createdAt: number;
  updatedAt: number;
  children: FolderTreeNode[];
  fileCount: number;        // Number of decks in this folder
  isExpanded?: boolean;
}

/**
 * Aggregate statistics for a folder
 * Computed from all decks within folder (and descendants if recursive)
 */
export interface FolderStats {
  totalDecks: number;
  totalCards: number;
  newCards: number;
  learningCards: number;
  reviewCards: number;
  dueToday: number;
  masteredCards: number;
  averageRetention: number;
  averageEase: number;
}
